#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="(fix|feat|merge|refactor|test): \[FCE-([0-9][0-9][0-9]{0,3})\].*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format: (fix|feat): \[FCE-\d{1,3}\].*$"
  echo "-"
  echo "For example: feat: [FCE-123] some message"
  echo "-"
  echo "Your commit message was:"
  echo $message
  exit 1
fi
